language: python
dist: xenial
sudo: true
cache: pip
env: CIBW_SKIP='*-win32 *-manylinux1_i686'
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt -q
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then export CIBW_BUILD='cp35*'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then export CIBW_BUILD='cp36*'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then export CIBW_BUILD='cp37*'; fi
  - pip install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
deploy:
  provider: pypi
  user: SimLeek
  skip_existing: true
  password:
    secure: vOLh1J0bGmxl/8lumyfhgKpE8+n1H2wGn5lhxRIM0+s5Ha8z3paSmErs7bBqJf1VzsVVkB7bmLX8vgijih9F6HXhBK35l6nQLDm1Iu6vplK08++sbCHIkcoRIOUiWcnu5jeIPBeRVM+EOdWtYFdhY6Ok/+JYpcmimZGRye9fYiY9hVNXWzL90sfkQ8J++3pA5ZqzwtcSBnI4ATnxQLR029GybTSAnLr4rzzgjdR/9d5DNmINeqyHaS9HNREmmJVCxxrsDJbAHXn6TKc4cCQmSNCmrEvXMsBxbOcUTmKWD5OqL17UErvjWcS0Iwx52IYNa0StpZ+BLKPX+rmzmbMVwuNZJho3M/9N7datKq6gvV7L7pTLI5+3720L3SoVZmlBuPCAXc+EDT6Xv1paLSvsAvt480kVqKA0EnCyAB5tk0SB7W34uIr+l6BwRbO8KH21Ckp+tZuvqaZdwvfR79xxxi9kUfOyvOMfid6SbG8pwmmeMybw7TCc493sRLUWiWuXtYG0CSxNS6O365IFqJFM0hWAPqBrr4XDfk6FCPYtlI7J6I1lnJUdDHX2dETzAo1knuAuL20pv5JcT4roPbxounKskRGVfs7d2WX7xzlXOh77noMrjeAndYeBnovbPaXalnmnTqnleRFoXjSjFmYP7gTINaF4fl6ffIMoXSNx8Ec=
