language: python
cache: pip
python:
- '3.5'
- '3.6'

install:
- pip install -r requirements.txt -q
script:
- if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then export CIBW_BUILD='cp35*'; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then export CIBW_BUILD='cp36*'; fi
- pip install cibuildwheel==0.10.1
- cibuildwheel --output-dir wheelhouse

deploy:
  provider: pypi
  user: SimLeek
  skip_existing: true
  password:
    secure: cM7WuD3r4Pl4n2pVH33GO/eVjO4E/7+QerW4WtFZ7F1C8HiBsCxiB7eKstErEjXgL7AoXIq8fL2zCGVA+a0ORXv/67/ho4j41uCdfITVVDxf6QKKahwnSAXoOux15gZMOtF5ky77h9siqD8mU2KCfwo2PzYpKF+sz1MQ8ibZFbYoeu1DR5CVQW8b1fGcAerBDv1fw74oamh7KrhKnRmBy6ooecEC+MV35cDRuGDXvXmV99VbLtsinNaUPVa1JXKVM3DxzXD0kjVJovauos7ALP5HdwLiPQj57r2jcbTAHOo74I2cAOeSKarco+LgGenyh/vDpo49Y+FyYJnAxZY4HtNOg7sekcIkULIj6t/db5VllcvE+Pn+n/ATzPYXxkvO9ossfBzWPSFlh6v39GtS+G92hkmTXT+VfsY3AAzke9QM16yljDo3sqb3kjzqtQfcslZ7JiIZTmzLD0zkcbdh7CmORboilJNKE2NgayRTI8zUJGqMMmvb2ZWIgJtSjeFUsuudjZyEeWNEYmHp3ypJsGW0thCLCgIS0XRdoKkH/azTkN2dgkxJh/DgXkXW4rQ2P3sMRIfWWi7oHjw+0jWWtILV6aE8I9lVgCMApjTPS9DWrMgwc0/Ojnuikg8dJMnVmTXXm0fMr9eyLaqjkTDkBVA9wDH4pynrbolUmHSc5BU=
